# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'kthPair:
#'
#'input: - x and y (numeric vectors; descending order)
#'       - n and m (lengths of x and y; integer)
#'       - k (index of element to choose; integer; 1 <= k <= n * m)
#'
kthPair <- function(x, y, k) {
    .Call('_robcp_kthPair', PACKAGE = 'robcp', x, y, k)
}

