// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// weightedMedian
double weightedMedian(NumericVector x, IntegerVector w);
RcppExport SEXP _robcp_weightedMedian(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(weightedMedian(x, w));
    return rcpp_result_gen;
END_RCPP
}
// kthPair
double kthPair(NumericVector x, NumericVector y, int k, int k2);
RcppExport SEXP _robcp_kthPair(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP k2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type k2(k2SEXP);
    rcpp_result_gen = Rcpp::wrap(kthPair(x, y, k, k2));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP c_cumsum(SEXP);
RcppExport SEXP c_cumsum_ma(SEXP, SEXP, SEXP);
RcppExport SEXP cholesky(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP CUSUM(SEXP, SEXP);
RcppExport SEXP CUSUM_ma(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP gen_matrix(SEXP, SEXP, SEXP);
RcppExport SEXP lrv(SEXP, SEXP, SEXP);
RcppExport SEXP lrv_matrix(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP lrv_subs_nonoverlap(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP lrv_subs_overlap(SEXP, SEXP);
RcppExport SEXP pKSdist(SEXP, SEXP);
RcppExport SEXP psi(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP u_hat(SEXP, SEXP, SEXP);
RcppExport SEXP wilcox(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_robcp_weightedMedian", (DL_FUNC) &_robcp_weightedMedian, 2},
    {"_robcp_kthPair", (DL_FUNC) &_robcp_kthPair, 4},
    {"c_cumsum",            (DL_FUNC) &c_cumsum,            1},
    {"c_cumsum_ma",         (DL_FUNC) &c_cumsum_ma,         3},
    {"cholesky",            (DL_FUNC) &cholesky,            5},
    {"CUSUM",               (DL_FUNC) &CUSUM,               2},
    {"CUSUM_ma",            (DL_FUNC) &CUSUM_ma,            5},
    {"gen_matrix",          (DL_FUNC) &gen_matrix,          3},
    {"lrv",                 (DL_FUNC) &lrv,                 3},
    {"lrv_matrix",          (DL_FUNC) &lrv_matrix,          5},
    {"lrv_subs_nonoverlap", (DL_FUNC) &lrv_subs_nonoverlap, 4},
    {"lrv_subs_overlap",    (DL_FUNC) &lrv_subs_overlap,    2},
    {"pKSdist",             (DL_FUNC) &pKSdist,             2},
    {"psi",                 (DL_FUNC) &psi,                 7},
    {"u_hat",               (DL_FUNC) &u_hat,               3},
    {"wilcox",              (DL_FUNC) &wilcox,              2},
    {NULL, NULL, 0}
};

RcppExport void R_init_robcp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
